### ISSUE TITLE
Using the same stamp to plot multiple images

### ISSUE THREAD

**Issue by FranzAtGithub** [trygvrad/colorstamps#2]
Hey there,

I want to draw many images with a code that could look roughly like this:

```python
for image in images:
    colorstamps.apply_stamp(                        
     image[:, :, 0], image[:, :, 1], 'fourCorners', 
     vmin_0=-1.5, vmax_0=1.5,             
     vmin_1=-1.5, vmax_1=1.5,             
 )
```

As I understand in each iteration a new `stamp` object is computed.
I do not understand what a "stamp" really is. For me it is a two dimensional colormap that is basically prescribed by the values `vmin_0`, `vmax_0`, `vmin_1`, `vmax_1` and `fourCorners`. If that is correct, than all stamp object generate in the loop would be "the same".

So here are my questions:
  - How bad is my understanding of stamps and are they really independent of the image?
  - How costly is the generation of a new stamp in very iteration?
  - Is it possible to generate a stamp without an image?
  - Is it possible to compute the stamp before the loop and use the same stamp for all images?
  
Thank you very much for building this package. It already helped me out a lot!

Best regards,
Franz

**Comment by trygvrad** [comment]
> How bad is my understanding of stamps and are they really independent of the image?
Think of the stamp as a container for the `cmap` (a 256x256x3 array), `vmin` and `vmax` parameters. 

> How costly is the generation of a new stamp in very iteration?

Not very. In your complete workflow I don't think this matters very much. The only computationally notable part is the `cmap` (see below)

> Is it possible to generate a stamp without an image?

Yes,  but there is no method to then apply it to an image, i.e. you can do the following:
```py
fig, ax = plt.subplots()
stamp = colorstamps.Stamp('fourCorners')
stamp.vmin_0 = -1.5
stamp.show_in_ax(ax)
```
![image](https://github.com/user-attachments/assets/3aea9c7a-f194-4ad0-8ce7-d823fda22bcb)

>   Is it possible to compute the stamp before the loop and use the same stamp for all images?

Unfortunately, it is not possible to reuse the stamp, but it is possible to reuse the `cmap`. In that you have to provide it as a numpy array, and not by name:

```py
images = np.random.random((4,10,10,2))*3-1
fig, axes = plt.subplots(1,4,figsize=(12,4))

cmap = colorstamps.get_cmap('fourCorners') # ← generates the cmap

for ax, image in zip(axes, images):
    rgb, stamp = colorstamps.apply_stamp(                        
                             image[:, :, 0], image[:, :, 1], cmap, 
                             vmin_0=-1.5, vmax_0=1.5,             
                             vmin_1=-1.5, vmax_1=1.5,    
                             )
    ax.imshow(rgb)
    stamp.overlay_ax(ax,
                lower_left_corner=[0.7,0.85], width=0.4)
```
![image](https://github.com/user-attachments/assets/16ecc729-20cb-4227-93fa-9464f93b647a)

**Comment by FranzAtGithub** [comment]
Hey, thank you very much for your response!

I will just go for something like this:
```python
import colorstamps
import matplotlib.pyplot as plt
import numpy as np

def apply(stamp, img):
    rgb, _ = colorstamps.apply_stamp(img[:, :, 0], img[:, :, 1],
                                     cmap=stamp.cmap,
                                     vmin_0=stamp.vmin_0, vmax_0=stamp.vmax_0,
                                     vmin_1=stamp.vmin_1, vmax_1=stamp.vmax_1)
    return rgb


stamp = colorstamps.Stamp('fourCorners')
stamp.vmin_0 = -1.5
stamp.vmax_0 = 1.5
stamp.vmin_1 = -1.5
stamp.vmax_1 = 1.5
images = np.random.random((8, 10, 10, 2))*3-1
fig , axes = plt.subplots(3, 3)

for image, ax in zip(images, axes.flatten()[[0, 1, 2, 3, 5, 6, 7, 8]]):
    ax.imshow(apply(stamp, image))

stamp.show_in_ax(axes[1, 1])
plt.show()
```

As I understand that generates a new `Stamp` object in each iteration but hides it.
Honestly, I think having an `apply(self, image)` method within `Stamp` would be a nice solution.
Also it would be nice if `Stamp.__init__` would take the vmin and vmax values as optional arguments.

Thank you again!
